### ISSUE TITLE
Помилка відкриття файлів .xaml (NuGet)

### ISSUE THREAD

**Issue by VSydorenko** [alex-kukhtin/A2v10.Web.Sample#2]
Я зробив все по оцій інструкції:

> Clone this repositiory
Open A2v10.Web.Sample.sln in Visual Studio
Create database a2v10sample
Execute ~\App_application@sql\platform\a2v10platform.sql
Execute ~\App_application@sql\platform\a2v10admin.sql
Execute ~\App_application@sql\sample_full.sql
Build solution

До бази даних підключився, в браузері запустилось.
Все, що потрібно для роботи, здається, працює (створення об'єктів, зберігання, перелінковка).

Ніяк не можу зрозуміть що не вистачає, щоб можна було попробувать редагувати файли .xaml
У вікні редагування відображається отака помилка:
![image](https://user-images.githubusercontent.com/50884937/159997980-c9250183-fd0d-4a83-a65b-5d71526baec3.png)

В інтернеті знайшов інструкцію, що Visual Studio його автоматично ремонтує, при зборці, але я її робив вже багато раз і це жодного результату не принесло.

Підкажіть, будь ласка, що потрібно встановити додатково або як той кеш справить.

**Comment by alex-kukhtin** [comment]
Запустіть Visual Studio Installer. Натисніть Modify та оберіть ось такі Workloads:
![image](https://user-images.githubusercontent.com/26379138/160053779-2f36032d-6f4c-4c7d-8802-885ff0d5a0f2.png)

**Comment by alex-kukhtin** [comment]
Дізайнер XAML працювате не буде. Це ж не WPF классичный. Текстова форма працює. Щоб виключити дізайнер, відключи його в Tools/Options.
![image](https://user-images.githubusercontent.com/26379138/160054228-c37f8b32-769c-4856-9434-02a6d7221cd2.png)

**Comment by alex-kukhtin** [comment]
При роботі з текстовим видом має працювати IntelliSence :-)

**Comment by VSydorenko** [comment]
Ситуація зрозуміла.
А візуалізацію форми під час розробки точно ніяк не можна реалізувати? щось складніше, ніж звичайну форму із полями вводу даних так реалізувати дуже складно, як мені здається...

**Comment by alex-kukhtin** [comment]
Звісно можна. Але це не просто. І часу займе дуже багато.
Останні роки всі пишуть розмітку (html/xaml) виключно текстом. Дізайнери не популярні. Згадайте FrontPage та інші "конструктори".

Це сумно, але так є.
